In [23]:
import numpy as np

c = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ],
    ]
)

In [19]:
zeros = np.zeros((5, 5), dtype=int)
zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

arange() function


The numpy arange() function creates a new numpy array with evenly spaced numbers between start (inclusive) and stop (exclusive) with a given step:
// numpy.arange(start, stop, step, dtype=None, *, like=None)


In [26]:
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

In [36]:
a = np.linspace(1, 10, 10)
a.prod()

3628800.0

In [33]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
average = np.mean(a, axis=1)
print(average)
average = np.mean(a, axis=0)
print(average)

[2. 5.]
[2.5 3.5 4.5]


In [38]:
import numpy as np

result = np.prod([
    [1, 2],
    [3, 4]
], axis=0,)

print(f'result={result}')

result=[3 8]


- What is NumPy
- CREATING ARRAYS
- Create NumPy Array
- ARRAY INDEXING & SLICING
- Indexing
- Slicing
- Fancy Indexing
- Boolean Indexing
- View vs. Copy
- AGGREGATE FUNCTIONS
- sum()
- mean()
- var()
- std()
- prod()
- amin()
- amax()
- all()
- any()

In [47]:
import numpy as np

a = np.array([0, 1, 2, 3, 4])

np.any(a > 5)
np.all(a >= 0)

True

In [49]:
import numpy as np

a = np.arange(1, 5)
print(a)

b = np.reshape(a, (2, 2))
print(b)

b.T

[1 2 3 4]
[[1 2]
 [3 4]]


array([[1, 3],
       [2, 4]])

In [51]:
import numpy as np

a = np.array([2, 3, 1])
b = np.sort(a)
b

array([1, 2, 3])

In [60]:
import numpy as np

a = np.array([
    [5, 3, 4],
    [2, 6, 1]
])

b = np.sort(a, axis=0)
print(b)

[[2 3 1]
 [5 6 4]]


In [71]:
import numpy as np

a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b = a.flatten()

# change element at index 0
b[0] = 0
print(b)

# display the array a
print(a)

# change element at index 0
# b[0] = 0
# print(b)
b = a.ravel()

# display the array a
print(b)
print(a)

[0 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [72]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

# Using ravel()
b = np.ravel(a)
print(f"Original array:\n{a}")
print(f"Flattened array:\n{b}")

# Modify the flattened array
b[0] = 5
print(f"Modified flattened array:\n{b}")
print(f"Corresponding element in the original array:\n{a[0, 0]}")

Original array:
[[1 2]
 [3 4]]
Flattened array:
[1 2 3 4]
Modified flattened array:
[5 2 3 4]
Corresponding element in the original array:
5


In [73]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

# Using flatten()
b = a.flatten()
print(f"Original array:\n{a}")
print(f"Flattened array:\n{b}")

# Modify the flattened array
b[0] = 5
print(f"Modified flattened array:\n{b}")
print(f"Corresponding element in the original array:\n{a[0, 0]}")

Original array:
[[1 2]
 [3 4]]
Flattened array:
[1 2 3 4]
Modified flattened array:
[5 2 3 4]
Corresponding element in the original array:
1


In [115]:
a = np.arange(0, 10)

ValueError: array split does not result in an equal division

In [117]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2], [3, 4]])


np.dot(a,b)

array([[ 7, 10],
       [15, 22]])

In [119]:
np.cross(a,b)

array([0, 0])

In [139]:
a = np.array([0,4,4])

a.any()

True

In [11]:
import numpy as np

a = np.array([[1, 2],[3,4]])
b = np.array([[2, 3],[4,5]])

c = a + b
d = np.add(a,b)
e = np.cross(a,b)
print(c)
print(d)
print(e)

[[3 5]
 [7 9]]
[[3 5]
 [7 9]]
[-1 -1]


In [30]:
import numpy as np

a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[1],[2]])

c = a + b
print(a.shape,b.shape)
print(c)
# b


(2, 3) (2, 1)
[[2 3 4]
 [6 7 8]]


In [47]:
import numpy as np

a = np.array([
    [1, 2],
    [3, 4]
])
b = np.array([
    [5, 6],
    [7, 8]
])

c = np.cross(a,b)
c

# c = np.vstack((a, b))
# print(c)

array([-4, -4])

In [57]:
import numpy as np


a = np.arange(1,12)
results = np.array_split(a,3)

print(a)
(results)


[ 1  2  3  4  5  6  7  8  9 10 11]


[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11])]